INSERT INTO "shopping_item" VALUES(1, 'Carrots, large');
INSERT INTO "shopping_item" VALUES(2, 'Onion, yellow, small');
INSERT INTO "shopping_item" VALUES(3, 'Onion, yellow, medium');
INSERT INTO "shopping_item" VALUES(4, 'Onion, yellow, large');
INSERT INTO "shopping_item" VALUES(5, 'Onion, red, small');
INSERT INTO "shopping_item" VALUES(6, 'Onion, red, medium');
INSERT INTO "shopping_item" VALUES(7, 'Onion, red, large');
INSERT INTO "shopping_item" VALUES(9, 'Milk, skim');
INSERT INTO "shopping_item" VALUES(10, 'Apple, Gala');
INSERT INTO "shopping_item" VALUES(11, 'Apple, Red Delicious');
INSERT INTO "shopping_item" VALUES(12, 'Apple, Fuji');
INSERT INTO "shopping_item" VALUES(13, 'Flour, All-purpose');
INSERT INTO "shopping_item" VALUES(14, 'Flour, bread');
INSERT INTO "shopping_item" VALUES(15, 'Cheese, deli, provolone');
INSERT INTO "shopping_item" VALUES(16, 'Cheese, deli, American');
INSERT INTO "shopping_item" VALUES(17, 'Cheese, deli, cheddar');
INSERT INTO "shopping_item" VALUES(18, 'Ham, deli');
INSERT INTO "shopping_item" VALUES(19, 'Cheese, deli');
INSERT INTO "shopping_item" VALUES(20, 'Cheese, cheddar');
INSERT INTO "shopping_item" VALUES(21, 'Tomato');
INSERT INTO "shopping_item" VALUES(22, 'Tomato, canned, crushed');
INSERT INTO "shopping_item" VALUES(23, 'Tomato, canned, whole');
INSERT INTO "shopping_item" VALUES(24, 'Tomato, canned, diced');
INSERT INTO "shopping_item" VALUES(25, 'Tomato, canned, Ro-Tel');
INSERT INTO "shopping_item" VALUES(26, 'Velveeta, low-fat, small');
INSERT INTO "shopping_item" VALUES(27, 'Velveeta, Mexican, small');
INSERT INTO "shopping_item" VALUES(28, 'Cat chow');
INSERT INTO "shopping_item" VALUES(29, 'Cheese, deli, swiss');
INSERT INTO "shopping_item" VALUES(30, 'Bread, sandwich');
INSERT INTO "shopping_item" VALUES(31, 'Pasta, linguini');
INSERT INTO "shopping_item" VALUES(32, 'Pasta, ravioli');
INSERT INTO "shopping_item" VALUES(33, 'Pasta, spaghetti');
INSERT INTO "shopping_item" VALUES(34, 'Banannas');
INSERT INTO "shopping_item" VALUES(35, 'Cereal');
INSERT INTO "shopping_item" VALUES(36, 'Cereal, Captain Crunch');
INSERT INTO "shopping_item" VALUES(37, 'Cereal, Wheat Chex');
INSERT INTO "shopping_item" VALUES(38, 'Cereal, Bran Chex');
INSERT INTO "shopping_item" VALUES(39, 'Cereal, Rice Chex');
INSERT INTO "shopping_item" VALUES(40, 'Cereal, Cheerios');
INSERT INTO "shopping_item" VALUES(41, 'Cheese, gorgonzolla');
INSERT INTO "shopping_item" VALUES(42, 'Cheese, blue');
INSERT INTO "shopping_item" VALUES(43, 'Cheese, gorgonzolla, crumbled');
INSERT INTO "shopping_item" VALUES(44, 'Soda, Coke Zero');
INSERT INTO "shopping_item" VALUES(45, 'Soda, Coke');
INSERT INTO "shopping_item" VALUES(46, 'Soda, Diet Coke');
INSERT INTO "shopping_item" VALUES(47, 'Wine, Syrah');
INSERT INTO "shopping_item" VALUES(48, 'Wine, Pinot Grigio');
INSERT INTO "shopping_item" VALUES(49, 'Wine, Prosecco');
INSERT INTO "shopping_item" VALUES(50, 'Wine, Zinfandel');
INSERT INTO "shopping_item" VALUES(51, 'Wine, Cava');
INSERT INTO "shopping_item" VALUES(52, 'Wine, Cabernet Sauvignon');
INSERT INTO "shopping_item" VALUES(53, 'Bread, french');
INSERT INTO "shopping_item" VALUES(54, 'Tissue, Kleenex');
INSERT INTO "shopping_item" VALUES(55, 'Toilet paper');
INSERT INTO "shopping_item" VALUES(56, 'Cherries');
INSERT INTO "shopping_item" VALUES(57, 'Wine, Pinot Noir');
INSERT INTO "shopping_item" VALUES(58, 'Garbage bags, kitchen');
INSERT INTO "shopping_item" VALUES(59, 'Blistex');
INSERT INTO "shopping_item" VALUES(60, 'Lysol kitchen cleaner');
INSERT INTO "shopping_item" VALUES(62, 'Crackers, Ritz');
INSERT INTO "shopping_item" VALUES(63, 'Crackers, Red Oval Stoned Wheat');
INSERT INTO "shopping_item" VALUES(64, 'Crackers, Table Water');
INSERT INTO "shopping_item" VALUES(65, 'Eggs');
INSERT INTO "shopping_item" VALUES(66, 'Chicken, breasts');
INSERT INTO "shopping_item" VALUES(67, 'Chicken, tenders');
INSERT INTO "shopping_item" VALUES(68, 'Chicken, rotisserie');
INSERT INTO "shopping_item" VALUES(69, 'Light bulbs, 60 watt');
INSERT INTO "shopping_item" VALUES(70, 'Light bulbs, 100 watt');
INSERT INTO "shopping_item" VALUES(71, 'Light bulbs, 25 watt');
INSERT INTO "shopping_item" VALUES(72, 'Onion, rolls');
INSERT INTO "shopping_item" VALUES(73, 'Alavert');
INSERT INTO "shopping_item_info" VALUES(1, 1, 14, '1');
INSERT INTO "shopping_item_info" VALUES(2, 1, 34, 'small bunch');
INSERT INTO "shopping_item_info" VALUES(3, 1, 16, '1/2 lb');
INSERT INTO "shopping_item_info" VALUES(4, 1, 54, '3');
INSERT INTO "shopping_item_info" VALUES(5, 1, 55, '1');
INSERT INTO "shopping_item_info" VALUES(6, 1, 56, 'small bag');
INSERT INTO "shopping_item_info" VALUES(7, 1, 29, '1');
INSERT INTO "shopping_item_info" VALUES(8, 1, 57, '1');
INSERT INTO "shopping_item_info" VALUES(9, 1, 58, 'large box');
INSERT INTO "shopping_item_info" VALUES(10, 1, 59, '1');
INSERT INTO "shopping_item_info" VALUES(11, 1, 60, '1');
INSERT INTO "shopping_item_info" VALUES(12, 1, 47, '1');
INSERT INTO "shopping_item_info" VALUES(13, 1, 28, '1');
INSERT INTO "shopping_item_info" VALUES(14, 1, 61, '1');
INSERT INTO "shopping_item_info" VALUES(15, 1, 44, '1');
INSERT INTO "shopping_item_info" VALUES(16, 1, 20, '1');
INSERT INTO "shopping_item_info" VALUES(17, 1, 62, '1');
INSERT INTO "shopping_item_info" VALUES(18, 1, 63, '1');
INSERT INTO "shopping_item_info" VALUES(19, 1, 64, '1');
INSERT INTO "shopping_item_info" VALUES(20, 2, 43, '1');
INSERT INTO "shopping_item_info" VALUES(21, 2, 8, '1');
INSERT INTO "shopping_item_info" VALUES(22, 2, 28, '1');
INSERT INTO "shopping_item_info" VALUES(23, 2, 37, '1');
INSERT INTO "shopping_item_info" VALUES(24, 2, 16, '1');
INSERT INTO "shopping_item_info" VALUES(25, 1, 1, '1');
INSERT INTO "shopping_item_info" VALUES(26, 2, 5, '1');
INSERT INTO "shopping_item_info" VALUES(27, 2, 25, '1');
INSERT INTO "shopping_item_info" VALUES(28, 1, 65, '1/2 dozen');
INSERT INTO "shopping_item_info" VALUES(29, 1, 8, '1');
INSERT INTO "shopping_item_info" VALUES(30, 1, 30, '1');
INSERT INTO "shopping_item_info" VALUES(31, 1, 9, '1/2 gallon');
INSERT INTO "shopping_item_info" VALUES(32, 1, 66, '1 lb');
INSERT INTO "shopping_item_info" VALUES(33, 1, 67, '1 lb');
INSERT INTO "shopping_item_info" VALUES(34, 1, 68, '1');
INSERT INTO "shopping_item_info" VALUES(35, 1, 35, '1');
INSERT INTO "shopping_item_info" VALUES(36, 1, 69, '1');
INSERT INTO "shopping_item_info" VALUES(37, 1, 70, '1');
INSERT INTO "shopping_item_info" VALUES(38, 1, 71, '1');
INSERT INTO "shopping_item_info" VALUES(39, 1, 37, '1');
INSERT INTO "shopping_item_info" VALUES(40, 1, 12, '1');
INSERT INTO "shopping_item_info" VALUES(41, 1, 10, '1');
INSERT INTO "shopping_item_info" VALUES(42, 1, 11, '1');
INSERT INTO "shopping_item_info" VALUES(43, 1, 53, '1');
INSERT INTO "shopping_item_info" VALUES(44, 1, 18, '1');
INSERT INTO "shopping_item_info" VALUES(45, 1, 7, '1');
INSERT INTO "shopping_item_info" VALUES(46, 1, 6, '1');
INSERT INTO "shopping_item_info" VALUES(47, 1, 5, '1');
INSERT INTO "shopping_item_info" VALUES(48, 1, 4, '1');
INSERT INTO "shopping_item_info" VALUES(49, 1, 3, '1');
INSERT INTO "shopping_item_info" VALUES(50, 1, 2, '1');
INSERT INTO "shopping_item_info" VALUES(51, 1, 21, '1');
INSERT INTO "shopping_item_info" VALUES(52, 1, 72, '1');
INSERT INTO "shopping_item_info" VALUES(53, 1, 73, '1');
INSERT INTO "shopping_list" VALUES(1, 'Next Trip', 1);
INSERT INTO "shopping_list" VALUES(2, 'Weekly', 1);
INSERT INTO "shopping_list" VALUES(4, 'Next Trip', 2);
INSERT INTO "shopping_list_item" VALUES(4, 58, 1, 'large box', 0);
INSERT INTO "shopping_list_item" VALUES(5, 59, 1, '1', 0);
INSERT INTO "shopping_list_item" VALUES(7, 43, 4, '6', 0);
INSERT INTO "shopping_list_item" VALUES(8, 8, 4, '1', 0);
INSERT INTO "shopping_list_item" VALUES(9, 37, 4, '1', 0);
INSERT INTO "shopping_list_item" VALUES(10, 16, 4, '1', 0);
INSERT INTO "shopping_list_item" VALUES(11, 5, 4, '1', 0);
INSERT INTO "shopping_list_item" VALUES(12, 25, 4, '1', 0);
INSERT INTO "shopping_list_item" VALUES(13, 65, 2, '1/2 dozen', 0);
INSERT INTO "shopping_list_item" VALUES(15, 30, 2, '1', 0);
INSERT INTO "shopping_list_item" VALUES(16, 9, 2, '1/2 gallon', 0);
INSERT INTO "shopping_list_item" VALUES(18, 69, 1, '1', 0);
INSERT INTO "shopping_list_item" VALUES(23, 30, 1, '1', 0);
INSERT INTO "shopping_list_item" VALUES(24, 60, 1, '1', 0);
INSERT INTO "shopping_list_item" VALUES(25, 72, 1, '1', 0);
INSERT INTO "shopping_list_item" VALUES(26, 73, 1, '1', 0);
INSERT INTO "siteuser" VALUES(1, 'doug', 'ntsucks', 'doug@hellfly.net', 'Athens, GA');
INSERT INTO "siteuser" VALUES(2, 'tmf', 'boolu', 'tmf-grocerific@hellfly.net', 'Athens, GA');
INSERT INTO "store" VALUES(1, 'Kroger', 'Athens, GA', 'College Station');
INSERT INTO "store" VALUES(2, 'Earthfare', 'Athens, GA', 'Five Points');
INSERT INTO "store" VALUES(3, 'Kroger', 'Athens, GA', 'Alps & Baxter');
INSERT INTO "store" VALUES(4, 'Kroger', 'Athens, GA', 'Epps Bridge / 316');
INSERT INTO "store" VALUES(5, 'Bi-Lo', 'Athens, GA', 'Milledge Ave.');
INSERT INTO "store" VALUES(6, 'Bells', 'Athens, GA', 'Hawthorne Ave.');
INSERT INTO "user_store" VALUES(1, 1, 1);
INSERT INTO "user_store" VALUES(2, 1, 2);
INSERT INTO "user_store" VALUES(3, 1, 3);
INSERT INTO "user_store" VALUES(4, 1, 4);
INSERT INTO "aisle_item" VALUES(1, 59, 2, '');
INSERT INTO "aisle_item" VALUES(2, 59, 1, 'Pharmacy');
INSERT INTO "aisle_item" VALUES(3, 12, 2, 'Produce');
INSERT INTO "aisle_item" VALUES(4, 12, 1, 'Produce');
INSERT INTO "aisle_item" VALUES(5, 10, 2, 'Produce');
INSERT INTO "aisle_item" VALUES(6, 10, 1, 'Produce');
INSERT INTO "aisle_item" VALUES(7, 11, 2, 'Produce');
INSERT INTO "aisle_item" VALUES(8, 11, 1, 'Produce');
INSERT INTO "aisle_item" VALUES(9, 34, 2, 'Produce');
INSERT INTO "aisle_item" VALUES(10, 34, 1, 'Produce');
INSERT INTO "aisle_item" VALUES(11, 53, 2, 'Bakery');
INSERT INTO "aisle_item" VALUES(12, 53, 1, 'Bakery');
INSERT INTO "aisle_item" VALUES(13, 1, 2, 'Produce');
INSERT INTO "aisle_item" VALUES(14, 1, 1, 'Produce');
INSERT INTO "aisle_item" VALUES(16, 56, 1, 'Produce');
INSERT INTO "aisle_item" VALUES(17, 66, 2, 'Butcher');
INSERT INTO "aisle_item" VALUES(18, 66, 1, 'Meat');
INSERT INTO "aisle_item" VALUES(19, 68, 2, '');
INSERT INTO "aisle_item" VALUES(20, 68, 1, 'Deli');
INSERT INTO "aisle_item" VALUES(21, 67, 2, 'Butcher');
INSERT INTO "aisle_item" VALUES(22, 67, 1, 'Meat');
INSERT INTO "aisle_item" VALUES(23, 18, 2, 'Deli');
INSERT INTO "aisle_item" VALUES(24, 18, 1, 'Deli');
INSERT INTO "aisle_item" VALUES(25, 7, 2, 'Produce');
INSERT INTO "aisle_item" VALUES(26, 7, 1, 'Produce');
INSERT INTO "aisle_item" VALUES(27, 6, 2, 'Produce');
INSERT INTO "aisle_item" VALUES(28, 6, 1, 'Produce');
INSERT INTO "aisle_item" VALUES(29, 5, 2, 'Produce');
INSERT INTO "aisle_item" VALUES(30, 5, 1, 'Produce');
INSERT INTO "aisle_item" VALUES(31, 4, 2, 'Produce');
INSERT INTO "aisle_item" VALUES(32, 4, 1, 'Produce');
INSERT INTO "aisle_item" VALUES(33, 3, 2, 'Produce');
INSERT INTO "aisle_item" VALUES(34, 3, 1, 'Produce');
INSERT INTO "aisle_item" VALUES(35, 2, 2, 'Produce');
INSERT INTO "aisle_item" VALUES(36, 2, 1, 'Produce');
INSERT INTO "aisle_item" VALUES(37, 21, 2, 'Produce');
INSERT INTO "aisle_item" VALUES(38, 21, 1, 'Produce');
INSERT INTO "aisle_item" VALUES(39, 59, 3, 'Pharmacy');
INSERT INTO "aisle_item" VALUES(40, 59, 4, 'Pharmacy');
INSERT INTO "aisle_item" VALUES(41, 72, 2, 'Bakery');
INSERT INTO "aisle_item" VALUES(42, 72, 3, '');
INSERT INTO "aisle_item" VALUES(43, 72, 1, '');
INSERT INTO "aisle_item" VALUES(44, 72, 4, '');
INSERT INTO "aisle_item" VALUES(46, 73, 3, 'Pharmacy');
INSERT INTO "aisle_item" VALUES(47, 73, 1, 'Pharmacy');
INSERT INTO "aisle_item" VALUES(48, 73, 4, 'Pharmacy');
INSERT INTO "aisle_item" VALUES(49, 73, 2, '');
INSERT INTO "aisle_item" VALUES(50, 65, 2, NULL);
INSERT INTO "aisle_item" VALUES(51, 65, 3, NULL);
INSERT INTO "aisle_item" VALUES(52, 65, 1, NULL);
INSERT INTO "aisle_item" VALUES(53, 65, 4, NULL);
