#!/bin/bash
#
# $Id: run_etags,v 1.12 2004/08/20 01:03:14 dhellmann Exp $
#
# Script to run etags against the source tree.
#

TAGFILE=~/Devel/Grocerific/TAGS
rm -f $TAGFILE

PY_SITE_PACKAGES=/Library/Frameworks/Python.framework/Versions/2.4/lib/python2.4/site-packages

echo -n "Running etags..."
find . $PY_SITE_PACKAGES \( -type f \( -name '*.py' \
						-o -name '*.[ch]' \
						-o -name 'dev_data.sql' \
						-o -name '*.sh' \
						-o -name '*.kid' \
			\) \) \
		-print \
		\
		| etags -l auto \
		-o $TAGFILE \
 		--regex='/[ \t]*\(create\|CREATE\)[ \t]+\(table\|TABLE\)[ \t]+\([^ (\t]+\)/\3/' \
  	    --regex='/[ \t]*self\.[a-z]+mgr[ \t]+=/\2/' \
		--regex='/[ \t]*\def[ \t]+\([^ :(\t]+\)/\1/' \
		--regex='/\([^ :(\t]+\)[ \t]*=/\1/' \
		--regex='/\(#\|--\| *\*+\) \$Id:[ \t]\(.*\),v[ \t]*/\2/' \
		-
echo "Done"
